name: Playwright Tests (with uv)
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: "latest"

      - name: Set Playwright Custom Path
        run: echo "PLAYWRIGHT_BROWSERS_PATH=$HOME/.cache/ms-playwright" >> $GITHUB_ENV

      - name: Install dependencies
        run: uv sync --frozen

      - name: Cache Playwright Browsers
        id: playwright-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('uv.lock') }}

      - name: Install Playwright Browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: uv run playwright install --with-deps chromium

      - name: Run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          uv run pytest ui/tests --html=report.html --self-contained-html

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: report.html